--liquibase formatted sql
--changeset ankit.kamboj:001.1
CREATE TABLE REVIEW (
  ID NUMBER NOT NULL AUTO_INCREMENT,
  REVIEW_DESC VARCHAR2(2000) NULL,
  RATING NUMBER NOT NULL,
  USER_NAME VARCHAR(255) NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
);
--rollback DROP TABLE REVIEW;
